include(CheckCXXCompilerFlag)

function(enable_cxx_compiler_flag_if_supported flag)
    set(CRATER_CXX_FLAGS ${CRATER_CXX_FLAGS})

    string(FIND "${CRATER_CXX_FLAGS}" "${flag}" flag_already_set)
    if(flag_already_set EQUAL -1)
        check_cxx_compiler_flag("${flag}" flag_supported)
    if(flag_supported)
        LIST(APPEND CRATER_CXX_FLAGS ${flag})
    endif()
        unset(flag_supported CACHE)
    endif()
    SET(CRATER_CXX_FLAGS ${CRATER_CXX_FLAGS} PARENT_SCOPE)
endfunction()
       
       
enable_cxx_compiler_flag_if_supported("-Wall")
enable_cxx_compiler_flag_if_supported("-Wextra")
enable_cxx_compiler_flag_if_supported("-Wcast-align")
enable_cxx_compiler_flag_if_supported("-Wcast-qual")
enable_cxx_compiler_flag_if_supported("-Wctor-dtor-privacy")
enable_cxx_compiler_flag_if_supported("-Wdisabled-optimization")
enable_cxx_compiler_flag_if_supported("-Wformat=2")
enable_cxx_compiler_flag_if_supported("-Winit-self")
enable_cxx_compiler_flag_if_supported("-Wlogical-op")
# enable_cxx_compiler_flag_if_supported("-Wmissing-declarations")
enable_cxx_compiler_flag_if_supported("-Wmissing-include-dirs")
enable_cxx_compiler_flag_if_supported("-Wnoexcept")
enable_cxx_compiler_flag_if_supported("-Wold-style-cast")
enable_cxx_compiler_flag_if_supported("-Woverloaded-virtual")
enable_cxx_compiler_flag_if_supported("-Wredundant-decls")
enable_cxx_compiler_flag_if_supported("-Wshadow")
enable_cxx_compiler_flag_if_supported("-Wsign-conversion")
enable_cxx_compiler_flag_if_supported("-Wsign-promo")
enable_cxx_compiler_flag_if_supported("-Wstrict-null-sentinel")
enable_cxx_compiler_flag_if_supported("-Wstrict-overflow=5")
enable_cxx_compiler_flag_if_supported("-Wswitch-default")
enable_cxx_compiler_flag_if_supported("-Wundef")
enable_cxx_compiler_flag_if_supported("-Wunused")
enable_cxx_compiler_flag_if_supported("-Wconversion")
enable_cxx_compiler_flag_if_supported("-Wmaybe-uninitialized")
enable_cxx_compiler_flag_if_supported("-Warray-bounds=2")
enable_cxx_compiler_flag_if_supported("-Wlifetime")
enable_cxx_compiler_flag_if_supported("-Wdouble-promotion")
enable_cxx_compiler_flag_if_supported("-Wnull-dereference")
enable_cxx_compiler_flag_if_supported("-Wduplicated-branches")
enable_cxx_compiler_flag_if_supported("-Wduplicated-cond")
enable_cxx_compiler_flag_if_supported("-Wmisleading-indentation")
enable_cxx_compiler_flag_if_supported("-Wno-comment")
enable_cxx_compiler_flag_if_supported("-Werror=return-type")
