[[actuations]]
time = 9
control_pos_mixed = [0, -5, 0, 0]

[[actuations]]
time = 12
control_pos_mixed = [0, 0, 0.5, 0]

[[actuations]]
time = 15
control_pos_mixed = [0, 0, 0, 0]

[[actuations]]
time = 16
control_pos_mixed = [0, 2.5, 0, 0]

[[actuations]]
time = 17
control_pos_mixed = [0, 5, 0, 0]

[[actuations]]
time = 18
control_pos_mixed = [0, 7.5, 0, 0]

[[actuations]]
time = 19
control_pos_mixed = [0, 10, 0, 0]