[sim]
t0 = { val = 0, type = "float" }
dt = { val = 0.01, type = "float" }

[sim.rocket]
max_t = { val = 120, type = "float" }
mass = { val = 2, type = "randfloat", dist = { type = "normal", mean = 2, std_dev = 0.1 } }

datcom_ref_pos = { val = [0.5, 0.0, 0.0], type = "float[]" }
engine_ref_pos = { val = [0.70, 0.0, 0.0], type = "float[]" }

xcg_body = { val = [0.55, 0.0, 0.0], type = "float[]" }

inertia_empty = { val = [
    0.005,
    0.0,
    0.0,
    0.0,
    0.26,
    0.0,
    0.0,
    0.0,
    0.26,
], type = "float[]" }
diameter = { val = 0.08, type = "randfloat", dist = { type = "normal", mean = 0.08, std_dev = 0.00026 } }
g_n = { val = [0, 0, 9.81], type = "float[]" }

# Used for magnetic field model
date = { val = "2025-09-14", type = "str" }

[sim.rocket.init]
azimuth = { val = 170, type = "randfloat", dist = { type = "normal", mean = 170, std_dev = 3 } }
elevation = { val = 84, type = "randfloat", dist = { type = "normal", mean = 84, std_dev = 0.5 } }
latitude = { val = 41.8080239, type = "float" }
longitude = { val = 14.0548082, type = "float" }
altitude = { val = 1411.211, type = "float" }

p0_n = { val = [0, 0, 0], type = "float[]" }
v0_b = { val = [0, 0, 0], type = "float[]" }
w0_b_deg = { val = [0, 0, 0], type = "float[]" }

[sim.rocket.disturbances]
const_force_b = { val = [0.0, 0.0, 0.0], type = "float[]" }
const_torque_b = { val = [0.0, 0.0, 0.0], type = "float[]" }

[sim.rocket.engine]
engine_type = { val = "tabulated", type = "str" }

[sim.rocket.engine.tabulated]
json_path = { val = "config/motor.json", type = "str" }

[sim.rocket.engine.simple]
total_impulse = { val = 320, type = "float" }
thrust_duration = { val = 6, type = "float" }

[sim.rocket.imu]
pos_r = { val = [0.0, 0.0, 0.0], type = "float[]" }
# Orientation of the IMU in the body frame (w component last)
quat_imu_b = { val = [0.0, 0.0, 0.0, 1.0], type = "float[]" }

[sim.rocket.magnetomer]
# Orientation of the magnetometer in the body frame (w component last)
quat_mag_b = { val = [0.0, 0.0, 0.0, 1.0], type = "float[]" }

[sim.rocket.aero.tabulated]
coeffs_main = { val = "coeffs_main.h5", type = "str" }
coeffs_dynamic = { val = "coeffs_dynamic.h5", type = "str" }

[sim.rocket.aero.linear]
cA_0 = { val = 0.3200, type = "float" }
cA_a = { val = -0.1725, type = "float" }
cA_b = { val = -0.1725, type = "float" }

cA_dy = { val = 0.4001, type = "float" }
cA_dp = { val = 0.4001, type = "float" }
cA_dr = { val = 0.5739, type = "float" }
cA_ds = { val = 0.8899, type = "float" }

cY_b = { val = -24.0744, type = "float" }
cY_r = { val = 154.0, type = "float" }
cY_dy = { val = 3.4045, type = "float" }

cN_a = { val = 24.0744, type = "float" }
cN_q = { val = 154.0, type = "float" }
cN_dp = { val = 3.4045, type = "float" }

cl_0 = { val = 0.01, type = "float" }
cl_p = { val = -19.0, type = "float" }
cl_dr = { val = 2.3963, type = "float" }

cm_a = { val = -37.2959, type = "float" }
cm_q = { val = -1813.0, type = "float" }
cm_dp = { val = 21.8445, type = "float" }

cn_b = { val = 37.2959, type = "float" }
cn_r = { val = -1813.0, type = "float" }
cn_dy = { val = 21.8445, type = "float" }

[sim.rocket.gnc.openloop]
sequence = { val = "config/openloop_seq.toml", type = "str" }
